openeats/feed/urls.py
from django.conf.urls import *
from views import RecentRecipesFeed,TopRecipesFeed

urlpatterns = [
    url(r'^recent/$', RecentRecipesFeed()),
    url(r'^top/$', TopRecipesFeed())]

openeats/list/urls.py
from django.conf.urls import url
from openeats.list import views as list_views

urlpatterns = [
    url(r'^grocery/$', list_views.index, name="grocery_list"),
    url(r'^grocery/recipe/(?P<recipe_slug>[-\w]+)/$', list_views.groceryAddRecipe, name='grocery_addrecipe'),
    url(r'^grocery/mail/(?P<gid>\d+)/$', list_views.groceryMail, name='grocery_mail'),
    url(r'^grocery/delete/(?P<id>\d+)/$', list_views.groceryDelete, name='grocery_delete'),
    url(r'^grocery/ajaxdelete/$', list_views.groceryAjaxDelete, name='grocery_Ajaxdelete'),
    url(r'^grocery/aisle/ajaxdelete/$', list_views.groceryAisleAjaxDelete, name="grocery_aisledelete"),
    url(r'^grocery/create/$', list_views.groceryCreate, name="grocery_create"),
    url(r'^grocery/edit/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryCreate, name='grocery_edit'),
    url(r'^grocery/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShow, name='grocery_show'),
    url(r'^grocery/print/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShow, {'template_name':'list/grocery_print.html',}, name='grocery_print'),
    url(r'^grocery/share/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShareList, name='grocery_share'),
    url(r'^grocery/unshare/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryUnShareList, name='grocery_unshare'),
    url(r'^grocery/grocery-ajax/$', list_views.groceryProfile, name="grocery_profile"),
    url(r'^grocery/aisle/$', list_views.groceryAisle, name="grocery_aisle")]

openeats/news/urls.py
from django.conf.urls import url
from openeats.news import views as news_views

urlpatterns = [
    url(r'^list/$', news_views.list, name="news_list"),
    url(r'^entry/(?P<slug>[\w-]+)/$', news_views.entry, name="news_entry")]

openeats/urls.py
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from django.contrib import admin

from accounts import views as accounts_views
from recipe import views as recipe_views

from registration.views import RegistrationView
register = RegistrationView.as_view()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^feed/', include('openeats.feed.urls')),
    url(r'^groups/', include('openeats.recipe_groups.urls')),
    url(r'^recipe/', include('openeats.recipe.urls')),
    url(r'^ingredient/', include('openeats.ingredient.urls')),
    url(r'^list/', include('openeats.list.urls')),
    url(r'^tags/', include('openeats.tags.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^news/', include('openeats.news.urls')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^$', recipe_views.index)]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openeats/list/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField

class GroceryList(models.Model):
    title = models.CharField(_("grocery list title"), max_length=250)
    slug = AutoSlugField(_('slug'), populate_from='title')
    author = models.ForeignKey(User, verbose_name=_('user'))
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['pub_date']

    def __unicode__(self):
        return self.title

    def get_shared(self):
        """check if the list is shared"""
        if GroceryShared.objects.filter(list=self):
            return True

    def get_shared_to(self):
        """if the list is shared get who it is shared to"""
        if self.get_shared:
            shared = GroceryShared.objects.get(list=self)
            return shared.shared_to

    def get_absolute_url(self):
        return "/grocery/%s/%s/" % (self.author, self.slug)


class GroceryAisle(models.Model):
    """simple table to hold aisle names for the grocery list"""
    aisle = models.CharField(_('aisle'), max_length=100)
    author = models.ForeignKey(User, verbose_name=_('user'), blank=True, null=True)

    class Meta:
        ordering = ['aisle']

    def __unicode__(self):
        return self.aisle


class GroceryItem(models.Model):
    list = models.ForeignKey(GroceryList, verbose_name=_('grocery list'), related_name='items')
    item = models.CharField(_("item"), max_length=550)
    aisle = models.ForeignKey(GroceryAisle, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    
    class Meta:
        ordering = ['aisle', 'item']

    def __unicode__(self):
        return self.item


class GroceryShared(models.Model):
    list = models.ForeignKey(GroceryList, verbose_name=_('grocery list'))
    shared_by = models.ForeignKey(User, verbose_name=_('shared by'), related_name="shared_by")
    shared_to = models.ForeignKey(User, verbose_name=_('shared to'), related_name="shared_to")

    class Meta:
        verbose_name_plural = "shared lists"

    def save(self, *args, **kwargs):
        """make sure the shared_by field is always set the to the owner of the list"""
        if not self.id:
            self.shared_by = self.list.author
        super(GroceryShared, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.list.title


class GroceryRecipe(models.Model):
    list = models.ForeignKey(GroceryList, verbose_name=_('grocery list'))
    recipe = models.ForeignKey('recipe.Recipe', verbose_name=_('recipe'))

    def __unicode__(self):
        return self.recipe.title

openeats/accounts/forms.py
from django.forms import ModelForm
from django import forms
from models import UserProfiles
from django.contrib.auth.models import User

class ProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        try:
            self.fields['email'].initial = self.instance.user.email
        except User.DoesNotExist:
            pass
    email = forms.EmailField(label="email")
   
    class Meta:
        model = UserProfiles
        exclude = ('user',)

    def save(self, *args, **kwargs):
        """
        Update the primary email address on the related User object as well.
        """
        u = self.instance.user
        u.email = self.cleaned_data['email']
        u.save()
        profile = super(ProfileForm, self).save(*args, **kwargs)
        return profile
      

openeats/recipe/forms.py
from django.forms import ModelForm
from django.template.loader import render_to_string
from models import Recipe
from django.apps import apps
import django.forms as forms
from django.forms.models import BaseInlineFormSet
from django.core.mail import EmailMessage, BadHeaderError
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.sites.models import Site
from django.template import loader, RequestContext
from django.http import HttpResponse


class SelectWithPop(forms.Select):
    """
    Add's a link to a select box to popup a form to allow you to add new items
    to a select box via a form. You need to include the js RelatedObjectLookups
    on the main form
    """
    def render(self, name, * args, ** kwargs):
        html = super(SelectWithPop, self).render(name, * args, ** kwargs)
        popupplus = render_to_string("recipe_groups/popupplus.html", {'field': name})
        return html + popupplus


class RecipeForm(ModelForm):
    """ Used to create new recipes the course and cuisine field are created with a
        speical widget that appends a link and graphic to the end of select field to allow
        users to add new items via a popup form
    """
    course_model = apps.get_model('recipe_groups','Course')
    cuisine_model = apps.get_model('recipe_groups','Cuisine')
    
    course = forms.ModelChoiceField(course_model.objects, widget=SelectWithPop)
    cuisine = forms.ModelChoiceField(cuisine_model.objects, widget=SelectWithPop)

    class Meta:
        model = Recipe
        exclude=('slug', 'ingredient')


class IngItemFormSet(BaseInlineFormSet):
    """Require at least two ingredient in the formset to be completed."""
    def clean(self):
        super(IngItemFormSet, self).clean()
        for error in self.errors:
            if error:
                return
        completed = 0
        for cleaned_data in self.cleaned_data:
            if cleaned_data and not cleaned_data.get('DELETE', False):
                completed += 1
        if completed < 2:
            raise forms.ValidationError("At least two %s are required." %
                                        self.model._meta.object_name.lower())


class RecipeSendMail(forms.Form):
    """Recipe form to send a recipe via email"""
    def __init__(self, data=None, files=None, request=None, *args, **kwargs):
        if request is None:
            raise TypeError("Keyword argument 'request must be supplies'")
        super(RecipeSendMail, self).__init__(data=data, files=files, *args, **kwargs)
        self.request = request

    to_email = forms.EmailField(widget=forms.TextInput(), label=_('email address'))
    id = forms.CharField(widget=forms.HiddenInput())
    from_site = Site.objects.get_current()

    def _get_recipe(self):
        if self.is_valid():
            recipe = Recipe.objects.get(pk=self.cleaned_data['id'])
            self.recipe = recipe
            return self.recipe
        else:
            raise ValueError(_('Can not get the recipe id from invalid form data'))


    def get_body(self):
        """get the recipe and return the message body for the email"""
        template_name = 'recipe/recipe_mail_body.html'  # template that contains the email body and also shared by the grocery print view
        message = loader.render_to_string(template_name, {'recipe': self._get_recipe()}, context_instance=RequestContext(self.request))
        return message

    def get_toMail(self):
        """gets the email to send the list to from the form"""
        if self.is_valid():
            return self.cleaned_data['to_email']
        else:
            raise ValueError(_('Can not get to_email from invalid form data'))

    def save(self, fail_silently=False):
        """ sends the email message"""
        self.subject = _(str(self.from_site) + ' recipe: ' + self._get_recipe().title)
        self.from_email =  self.request.user.email
        if self.subject and self.get_body() and self.from_email:
            try:
                msg = EmailMessage(self.subject, self.get_body(), self.from_email, [self.get_toMail()])
                msg.content_subtype = 'html'
                msg.send()
            except BadHeaderError:
                return HttpResponse(_('Invalid header found.'))
            return HttpResponse(_('Email Sent'))
        else:
            return HttpResponse('Make sure all fields are entered and valid.')

openeats/accounts/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext
from django.conf import settings
from django.contrib import messages
from django.utils.translation import ugettext as _


def logout_page(request):
    """this replaces the normal logout view found in django.contrib.auth with a view that logs the user out and redirects them to the main page
       and displays a message
    """

    logout(request)
    output = _('You have been logged out!.')
    messages.success(request, output)
    return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)


def signIn_page(request):
    """This combines the sign in and the create user forms into one page using jquery UI tabs and is called from the nav bar"""

    return render(request,'accounts/signIn_page.html')

openeats/feed/views.py
from django.contrib.syndication.views import Feed
from django.conf import settings
from django.utils.translation import ugettext as _
from openeats.recipe.models import Recipe


class RecentRecipesFeed(Feed):
    title = settings.OETITLE + _(" Recent Recipes")
    link = "/recipe/recent/"
    description = _("Updates added on new recipes added to ") + settings.OETITLE

    def items(self):
        return Recipe.objects.filter(shared=Recipe.SHARE_SHARED).order_by('-pub_date', 'title')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.info


class TopRecipesFeed(Feed):
    title = settings.OETITLE + _(" Top Recipes")
    link = "/recipe/top/"
    description =_("Top recipes on ") + settings.OETITLE

    def items(self):
        rating_qs = Recipe.objects.extra(select={'rate': '((100/%s*rating_score/(rating_votes+%s))+100)/2' % (Recipe.rating.range, Recipe.rating.weight)})
        return rating_qs.filter(shared=Recipe.SHARE_SHARED).order_by('-rate')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.info

openeats/ingredient/views.py
from django.http import HttpResponse
from models import Ingredient

import json

def autocomplete_ing(request):
    """Used to auto complete ingredient names on the recipe form. This view is called by a jquery script
       returns json list of ten ingredients found
    """
    
    q = request.GET.get('term', '')
    ing_list = Ingredient.objects.filter(title__istartswith=q).values_list('title').distinct().order_by('title')[:10]
    results = []
    for ing_item in ing_list:
        results.append(" ".join(ing_item))
    return HttpResponse(json.dumps(results), mimetype="application/json")

openeats/news/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from models import Entry


def entry(request, slug):
    """returns one news entry"""
    entry = get_object_or_404(Entry, slug=slug)
    return render_to_response('news/entry.html', {'entry': entry}, context_instance=RequestContext(request))


def list(request):
    """returns a list of news stories"""
    entry_list = Entry.objects.all().order_by('pub_date')
    return render_to_response('news/entry_list.html', {'entry_list': entry_list}, context_instance=RequestContext(request))

openeats/recipe_groups/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.generic import ListView
from django.views.generic.edit import  CreateView, UpdateView
from django.core.urlresolvers import reverse_lazy
from models import Course, Cuisine
from openeats.recipe.models import Recipe
from django.contrib.auth.decorators import login_required
from forms import CoursePopForm, CuisinePopForm
from openeats.helpers.form_helper import handlePopAdd


def course_recipes(request, slug):
    """Rectrives the recipe objects in a list that belong to the course passed to the method"""
    course_object = get_object_or_404(Course, slug=slug)
    recipe_list = course_object.recipe_set.filter(shared=Recipe.SHARE_SHARED)
    
    return render_to_response('recipe_groups/recipe_list.html', {'recipe_list': recipe_list, 'category': course_object.title}, context_instance=RequestContext(request))


def cuisine_recipes(request, slug):
    """Retrives the recipe objects in a list that belong to the cuisine passed to the method"""
    cuisine_object = get_object_or_404(Cuisine, slug=slug)
    recipe_list = cuisine_object.recipe_set.filter(shared=Recipe.SHARE_SHARED)
       
    return render_to_response('recipe_groups/recipe_list.html', {'recipe_list': recipe_list, 'category': cuisine_object.title}, context_instance=RequestContext(request))


@login_required
def course_pop(request):
    """Is called via js from the recipe form to allow users to add a new course with out leaving the recipe form"""
    return handlePopAdd(request, CoursePopForm, 'course')


@login_required
def cuisine_pop(request):
    """Is called via js from the recipe form to allow users to add a new cuisine with out leaving the recipe form"""
    return handlePopAdd(request, CuisinePopForm, 'cuisine')


class CourseList(ListView):
    context_object_name = 'course'
    queryset = Course.objects.all()


class CuisineList(ListView):
    context_object_name = 'cuisine'
    queryset = Cuisine.objects.all()


class CourseCreate(CreateView):
    model = Course
    success_url = reverse_lazy('recipe')


class CourseUpdate(UpdateView):
    model = Course


class CuisineCreate(CreateView):
    model = Cuisine
    template_name = 'recipe_groups/course_form.html'
    success_url = reverse_lazy('recipe')


class CuisineUpdate(UpdateView):
    model = Cuisine

openeats/tags/views.py
from taggit.models import Tag, TaggedItem
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404


def recipeTags(request, tag):
    """displays a list of recipes with a giving tag"""
    recipe_tag = get_object_or_404(Tag, slug=tag)
    recipes_tagged = TaggedItem.objects.filter(tag=recipe_tag)
    recipe_list = []
    for recipe in recipes_tagged:
        recipe_list.append(recipe.content_object)

    return render_to_response('tags/recipe_tags.html', {'recipe_list': recipe_list}, context_instance=RequestContext(request))

openeats/templates/list/_aisles.html
{% comment %}Called by groceryaisle_form.html to load the current aisles for a user and is called by ajaz when an aisle is removed on that form{% endcomment %}

{% load i18n %}
{% block jscript %}
   <script type="text/javascript">
        $(function () {
            $(".remove-aisle").click( function () {
                var id = $(this).attr("id");
                $.post('/list/grocery/aisle/ajaxdelete/', {'id': id},
                function (data) {
                   $("#user_aisles").fadeOut('slow').html(data).fadeIn('slow');
                });
            });
        });
    </script>
{% endblock %}

<h2>{% trans 'Current Aisles' %}</h2>
    <ul class="well">
    {% for aisle in aisles %}
        <li>{{ aisle }}<a href ="#" id="{{ aisle.id}}" class="remove-aisle"><img title="remove" alt="remove" src="{{ STATIC_URL }}/images/delete.png" /></a></li>
    {% empty %}
        {% trans "you have not created any aisles yet!" %}
    {% endfor %}
   </ul>

openeats/templates/list/_items.html
<div class="row">
    <div class="col-sm-3">
        <div class="list-group">
            {% for aisle in aisle_list %}
                <h4 class="list-group-item-heading list-group-item-info navheader">{{ aisle }}</h4>
                {% for item in items %}
                    {% if item.aisle == aisle %}
                        <li class="list-group-item">{{ item }}</li>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>

openeats/templates/list/_list.html
{% comment %}This template is called by other templates to display a list of grocery list, the template is passed a grocery list object from a list of grocery objects{% endcomment %}

{% load i18n %}
{% load sanitize %}

<div class="well grocery">
   <h3><a href="{% url 'grocery_show' user=list.author slug=list.slug %}">{{ list }}</a></h3>
   <hr />
   <span class="create-date">{% trans 'created on ' %} {{ list.pub_date }}</span>
   <ul>
     {%for item in list.items.all|slice:":5" %}
       <li>{{ item }}</li>
     {% endfor %}
    </ul>
</div>

openeats/templates/list/grocery_addrecipe.html
{% extends 'list/grocery_base.html' %}
{% load i18n %}
{% block title %}{{ block.super }}| {{ recipe }}|{% trans 'grocery list' %} {% endblock %}

{% block content %}
  <form class="well form-inline" action="" method="post">{% csrf_token %}
    {{  form.errors }} {{  form.non_field_errors }}
    {{ form.as_p }}
    <input type='hidden' name='recipe_id' value="{{ recipe.id }}" />
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">{% trans 'save' %}</button>
      <a class="btn" href="{% url 'recipe_index' %}">{% trans 'cancel' %}</a>
    </div>
   </form>
{% endblock %}

openeats/templates/list/grocery_ajax.html
{% comment %}This template is used via an ajax call from the users profile page to display all the grocery list for a giving user {% endcomment %}
{% load i18n %}
<html>
  <head>
    <script type="text/javascript">
      $(function () {
        $(".remove-grocery").click( function () {
           var id = $(this).attr("id");
           $.post('/list/grocery/ajaxdelete/', {'id': id},
           function (data) {
             $("#glist").hide().html(data).fadeIn('slow');
           });
        });
      });
    </script>
  </head>
   <body>
     <div id="glist">
       {% if lists|length > 0 %}
         {% for list in lists %}
           <a href ="#" onclick="return confirm('Are you sure you want to delete?')" id="{{ list.id}}" class="remove-grocery"><img title="remove" alt="remove" src="{{ STATIC_URL }}/images/remove.gif" /></a>
           {% include '/list/_list.html' %}
         {% endfor %}
         {% else %}
           <p>{% trans 'You have not added any grocery list yet!' %}</p>
           <p><a href="{% url 'grocery_create' %}"> {% trans 'create a grocery list' %}</a></p>
      {% endif %}
      </div>
   </body>
</html>

openeats/templates/list/grocery_base.html
{% extends 'base.html' %}
{% load i18n %}
{%  block sidebar %}
    {% include 'sidebar/grocery.html' %}
    
{% endblock %}
{% block content %}
{% endblock %}

openeats/templates/list/grocery_detail.html
{% extends 'list/grocery_base.html' %}
{% load i18n %}
{% block title %}{{ block.super }} | {{ list.author }} | {% trans 'grocery list' %} {% endblock %}

{% block content %}
    {% if list.get_shared %}
        <div class="alert alert-info">
            {% trans 'this list is currently shared by' %} {{ list.author }} {% trans 'to user' %} {{ list.get_shared_to }}
        </div>
    {% endif %}
    <h2>{{ list.author}} {% trans 'grocery list -' %} {{ list.title }}</h2>
    <div class="well">
        {% if list.author == request.user %}
          <a href="{% url 'grocery_delete' id=list.id %}" onclick="return confirm('Are you sure you want to delete?')" >
            <img class="grocery-delete" src="{{STATIC_URL}}/images/remove.gif" alt="remove"/></a>
        {% endif %}
        {% load grocery_item %}
        {% item_tag list.items.all %}
    </div>
{% endblock %}

openeats/templates/list/grocery_email.html
{%  load i18n %}
<div>
    <form action="{% url 'grocery_mail' gid=gid %}" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="gid" value="{{ gid }}" />
        
    </form>
</div>

openeats/templates/list/grocery_index.html
{% extends 'list/grocery_base.html' %}
{% load i18n %}
{% block title %} {{ block.super }} {% trans 'Grocery List' %}{% endblock %}

{% block content %}
  <h2>{{ request.user }} {%trans 'grocery list'%}</h2>
    <div class="well" >
      {% for glist in glists %}
        <div class="{% cycle 'grow1' 'grow2' %} grocery-detail">
          <a href="{% url 'grocery_delete' id=glist.id %}" onclick="return confirm('Are you sure you want to delete?')">
            <img class="grocery-delete" src="{{STATIC_URL}}/images/remove.gif" alt="remove"/></a>
          <h3><a href="{% url 'grocery_show' user=glist.author slug=glist.slug %}">{{ glist }}</a></h3>
          <span class="create-date">{% trans 'created on ' %} {{ glist.pub_date }}</span>
          <ul class="list-group">
            {%for item in  glist.items.all|slice:":5" %}
              <li class="list-group-item">{{ item }}</li>
            {% endfor %}
          </ul>
        </div>
        <hr />

      {% empty %}
        <h3>{%trans 'You do not have any grocery list created' %}</h3>
        <p><a href="{% url 'grocery_create' %}"> {% trans 'create a grocery list' %}</a></p>
      {% endfor %}

      {% if gshared %}
        <h1>{% trans 'shared list' %}</h1>
        {% for shared in gshared %}
          <div class="{% cycle 'grow1' 'grow2' %} grocery-detail">
            <h3><a href="{% url 'grocery_show' user=shared.shared_by slug=shared.list.slug %}">{{ shared.list.title }}</a></h3>
            <a href="{% url 'grocery_unshare' slug=shared.list.slug user=shared.shared_to %}" onclick="return confirm('Are you sure you want to delete?')">
              <img class="grocery-delete" src="{{STATIC_URL}}/images/remove.gif" alt="remove"/></a>
            <span class="create-date">{% trans 'shared by ' %} {{ shared.shared_by }}</span>
            <ul>
             {%for item in  shared.list.items.all|slice:":5" %}
              <li>{{ item }}</li>
             {% endfor %}
            </ul>
          </div>
          <hr/>
         {% endfor %}
      {% endif %}
  </div>
{% endblock %}

openeats/templates/list/grocery_mail_body.html
{% comment %}This template is the template for the grocery list email body{% endcomment %}
{% load i18n %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" media="print" href="http://{{ request.get_host }}{{STATIC_URL}}css/grocery_print.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="http://{{ request.get_host }}{{STATIC_URL}}css/grocery_prints.css" />
        <title>{{ OETITLE }}{% trans 'Email'%} {{ list }}</title>
    </head>
    <body>
        <div id="grocery-print">
            <img src="http://{{ request.get_host }}{{ OELOGO }}" alt="OpenEats logo" />
            <h2>{% trans 'grocery list ' %}{{ list }}</h2>
                {% load grocery_item %}
                {% item_tag list.items.all %}
        </div>
    </body>
</html>

openeats/templates/list/grocery_print.html
{% comment %}This template is the template for the recipe print view{% endcomment %}
{% load i18n %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" media="print" href="{{STATIC_URL}}css/grocery_print.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="{{STATIC_URL}}css/grocery_prints.css" />
        <title>{{ OETITLE }} {% trans 'Print'%} {{ list }}</title>
    </head>
    <body>
        <a id="notvisable" href="javascript:window.print()">Print</a>
        <div id="grocery-print">
            <img src="{{ OELOGO }}" alt="OpenEats logo" />
            <h2>{% trans 'grocery list ' %}{{ list }}</h2>
                {% load grocery_item %}
                {% item_tag list.items.all %}
        </div>
    </body>
</html>

openeats/templates/list/grocerylist_form.html
{% extends 'list/grocery_base.html' %}
{% load i18n %}
{% block jscript %}
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery/jquery.formset.js"></script>
  <script type="text/javascript">
    $(function() {
      $('#grocery-form tbody tr').formset({
        prefix: '{{ formset.prefix }}',
        extraClasses: ['row1', 'row2'],
        deleteText: ''
      });
    })
  </script>
{% endblock %}

{% block content %}
  <form class="form-horizontal" id="grocery-form" action="" method="post">{% csrf_token %}
    <fieldset>
      <legend>{% trans 'grocery list' %}</legend>
      <input type="hidden" id="id_author" name="author" value="{{ user.id }}" />
      <div class="control-group">
        <label class="control-label" for="id_{{ form.title.name}}">{{ form.title.label|lower }}</label>
        <div class="controls">
         {{ form.title }}{{ form.title.errors }}
        </div>
      </div>
    </fieldset>
    <fieldset>
      <legend>{% trans 'items' %}</legend>
      <p>{{  formset.non_form_errors }}</p>
      <table class="table table-bordered"id="list-grid">
        <tbody>
          {% for form in formset.forms %}
            <tr id="{{ form.prefix }}-row" class="{% cycle 'row1' 'row2' %}">
              <td>
                {% for hid in form.hidden_fields %}{{ hid }}{% endfor %}
                {% if form.instance.pk %} {{  form.DELETE }}{% endif %}
                {{ form.item.errors }} {{ form.item.label_tag|lower }}
              </td>
              <td class="item">{{ form.item }}</td>
              <td>{{ form.aisle.errors }} {{ form.aisle.label_tag|lower }}</td>
              <td class="aisle">{{ form.aisle }}</td>
            </tr>
         {% endfor %}
        </tbody>
      </table>
    </fieldset>
    <div class="form-actions">
      {{ formset.management_form }}
       <button type="submit" class="btn btn-primary">{% trans 'save list' %}</button>
       <a class="btn" href="{% url 'grocery_list' %}">{% trans 'cancel' %}</a>
    </div>
  </form>
{% endblock %}