openeats/feed/urls.py
from django.conf.urls import *
from views import RecentRecipesFeed,TopRecipesFeed

urlpatterns = [
    url(r'^recent/$', RecentRecipesFeed()),
    url(r'^top/$', TopRecipesFeed())]

openeats/list/urls.py
from django.conf.urls import url
from openeats.list import views as list_views

urlpatterns = [
    url(r'^grocery/$', list_views.index, name="grocery_list"),
    url(r'^grocery/recipe/(?P<recipe_slug>[-\w]+)/$', list_views.groceryAddRecipe, name='grocery_addrecipe'),
    url(r'^grocery/mail/(?P<gid>\d+)/$', list_views.groceryMail, name='grocery_mail'),
    url(r'^grocery/delete/(?P<id>\d+)/$', list_views.groceryDelete, name='grocery_delete'),
    url(r'^grocery/ajaxdelete/$', list_views.groceryAjaxDelete, name='grocery_Ajaxdelete'),
    url(r'^grocery/aisle/ajaxdelete/$', list_views.groceryAisleAjaxDelete, name="grocery_aisledelete"),
    url(r'^grocery/create/$', list_views.groceryCreate, name="grocery_create"),
    url(r'^grocery/edit/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryCreate, name='grocery_edit'),
    url(r'^grocery/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShow, name='grocery_show'),
    url(r'^grocery/print/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShow, {'template_name':'list/grocery_print.html',}, name='grocery_print'),
    url(r'^grocery/share/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryShareList, name='grocery_share'),
    url(r'^grocery/unshare/(?P<user>[-\w]+)/(?P<slug>[-\w]+)/$', list_views.groceryUnShareList, name='grocery_unshare'),
    url(r'^grocery/grocery-ajax/$', list_views.groceryProfile, name="grocery_profile"),
    url(r'^grocery/aisle/$', list_views.groceryAisle, name="grocery_aisle")]

openeats/news/urls.py
from django.conf.urls import url
from openeats.news import views as news_views

urlpatterns = [
    url(r'^list/$', news_views.list, name="news_list"),
    url(r'^entry/(?P<slug>[\w-]+)/$', news_views.entry, name="news_entry")]

openeats/urls.py
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from django.contrib import admin

from accounts import views as accounts_views
from recipe import views as recipe_views

from registration.views import RegistrationView
register = RegistrationView.as_view()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^feed/', include('openeats.feed.urls')),
    url(r'^groups/', include('openeats.recipe_groups.urls')),
    url(r'^recipe/', include('openeats.recipe.urls')),
    url(r'^ingredient/', include('openeats.ingredient.urls')),
    url(r'^list/', include('openeats.list.urls')),
    url(r'^tags/', include('openeats.tags.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^news/', include('openeats.news.urls')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^$', recipe_views.index)]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openeats/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class UserProfiles(models.Model):
    user = models.OneToOneField(User, verbose_name=_('user'))
    about = models.TextField(_('about'), blank=True,default="Tell everyone something about yourself")
    url = models.URLField(_('url'), blank=True)
    location = models.CharField(_('location'), max_length=150, blank=True, default='')
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = _('User profiles')
        
    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        return ('profiles_profile_detail', (), {'username': self.user.username})

    get_absolute_url = models.permalink(get_absolute_url)
    

openeats/list/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField

class GroceryList(models.Model):
    title = models.CharField(_("grocery list title"), max_length=250)
    slug = AutoSlugField(_('slug'), populate_from='title')
    author = models.ForeignKey(User, verbose_name=_('user'))
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['pub_date']

    def __unicode__(self):
        return self.title

    def get_shared(self):
        """check if the list is shared"""
        if GroceryShared.objects.filter(list=self):
            return True

    def get_shared_to(self):
        """if the list is shared get who it is shared to"""
        if self.get_shared:
            shared = GroceryShared.objects.get(list=self)
            return shared.shared_to

    def get_absolute_url(self):
        return "/grocery/%s/%s/" % (self.author, self.slug)


class GroceryAisle(models.Model):
    """simple table to hold aisle names for the grocery list"""
    aisle = models.CharField(_('aisle'), max_length=100)
    author = models.ForeignKey(User, verbose_name=_('user'), blank=True, null=True)

    class Meta:
        ordering = ['aisle']

    def __unicode__(self):
        return self.aisle


class GroceryItem(models.Model):
    list = models.ForeignKey(GroceryList, verbose_name=_('grocery list'), related_name='items')
    item = models.CharField(_("item"), max_length=550)
    aisle = models.ForeignKey(GroceryAisle, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    
    class Meta:
        ordering = ['aisle', 'item']

    def __unicode__(self):
        return self.item


class GroceryShared(models.Model):
    list = models.ForeignKey(GroceryList, verbose_name=_('grocery list'))
    shared_by = models.ForeignKey(User, verbose_name=_('shared by'), related_name="shared_by")
    shared_to = models.ForeignKey(User, verbose_name=_('shared to'), related_name="shared_to")

    class Meta:
        verbose_name_plural = "shared lists"

    def save(self, *args, **kwargs):
        """make sure the shared_by field is always set the to the owner of the list"""
        if not self.id:
            self.shared_by = self.list.author
        super(GroceryShared, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.list.title


class GroceryRecipe(models.Model):
    list = models.ForeignKey(GroceryList, verbose_name=_('grocery list'))
    recipe = models.ForeignKey('recipe.Recipe', verbose_name=_('recipe'))

    def __unicode__(self):
        return self.recipe.title

openeats/recipe/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django_extensions.db.fields import AutoSlugField
from django.utils.translation import ugettext_lazy as _

class Recipe(models.Model):
    SHARE_SHARED = 0
    PRIVATE_SHARED = 1
    SHARED_CHOCIES = (
        (SHARE_SHARED, _('Share')),
        (PRIVATE_SHARED, _('Private')),
    )

    title = models.CharField(_("Recipe Title"), max_length=250)
    author = models.ForeignKey(User, verbose_name=_('user'))
    slug = AutoSlugField(_('slug'), populate_from='title', unique=True)

    servings = models.IntegerField(_('servings'), help_text="enter total number of servings", default=0)
    info = models.TextField(_('info'), help_text="enter information about the recipe", default='')
    directions = models.TextField(_('directions'), default='')
    cook_time = models.IntegerField(_('cook time'), help_text="enter time in minutes", default=0)
    photo = models.ImageField(_('photo'), blank=True, upload_to="upload/recipe_photos", null=True)

    course = models.ForeignKey('recipe_groups.Course', verbose_name=_('course'), default=0)
    cuisine = models.ForeignKey('recipe_groups.Cuisine', verbose_name=_('cuisine'), default=0)
    shared = models.IntegerField(_('shared'), choices=SHARED_CHOCIES, null=True, 
                                 default=SHARE_SHARED, help_text="share the recipe with the community or mark it private")
    tags = TaggableManager(_('tags'), help_text="separate with commas", blank=True)
    related = models.OneToOneField('Recipe', verbose_name=_('related'), related_name='RecipeRelated', 
                                   blank=True, null=True, help_text="relate another recipe")
    
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['pub_date', 'title']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/recipe/%s/" % str(self.id)

    def get_reported(self):
        if ReportedRecipe.objects.filter(recipe=self):
            return True        


class StoredRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, verbose_name=_('recipe'))
    user = models.ForeignKey(User, verbose_name=_('user'))

    def __unicode__(self):
        return self.recipe.title


class NoteRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, verbose_name=_('recipe'))
    author = models.ForeignKey(User, verbose_name=_('author'))
    text = models.TextField(_('note'))

    class meta:
        verbose_name_plural = "Recipe Notes"

    def __unicode__(self):
        return "%s note for %s" % (self.author, self.recipe)


class ReportedRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, verbose_name=_('recipe'))
    reported_by = models.ForeignKey(User, verbose_name=_('author'))
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['pub_date', 'recipe']
    
    def __unicode__(self):
        return self.recipe.title

openeats/accounts/forms.py
from django.forms import ModelForm
from django import forms
from models import UserProfiles
from django.contrib.auth.models import User

class ProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        try:
            self.fields['email'].initial = self.instance.user.email
        except User.DoesNotExist:
            pass
    email = forms.EmailField(label="email")
   
    class Meta:
        model = UserProfiles
        exclude = ('user',)

    def save(self, *args, **kwargs):
        """
        Update the primary email address on the related User object as well.
        """
        u = self.instance.user
        u.email = self.cleaned_data['email']
        u.save()
        profile = super(ProfileForm, self).save(*args, **kwargs)
        return profile
      

openeats/recipe_groups/forms.py
from django.forms import ModelForm
from models import Course, Cuisine


class CoursePopForm(ModelForm):
    """form object for the popup from the recipe_form to add a new course"""
    class Meta:
        model = Course
        exclude = ('slug',)


class CuisinePopForm(ModelForm):
    """form object for the popup from the recipe_form to add a new cuisine"""
    class Meta:
        model = Cuisine
        exclude = ('slug',)

openeats/accounts/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext
from django.conf import settings
from django.contrib import messages
from django.utils.translation import ugettext as _


def logout_page(request):
    """this replaces the normal logout view found in django.contrib.auth with a view that logs the user out and redirects them to the main page
       and displays a message
    """

    logout(request)
    output = _('You have been logged out!.')
    messages.success(request, output)
    return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)


def signIn_page(request):
    """This combines the sign in and the create user forms into one page using jquery UI tabs and is called from the nav bar"""

    return render(request,'accounts/signIn_page.html')

openeats/feed/views.py
from django.contrib.syndication.views import Feed
from django.conf import settings
from django.utils.translation import ugettext as _
from openeats.recipe.models import Recipe


class RecentRecipesFeed(Feed):
    title = settings.OETITLE + _(" Recent Recipes")
    link = "/recipe/recent/"
    description = _("Updates added on new recipes added to ") + settings.OETITLE

    def items(self):
        return Recipe.objects.filter(shared=Recipe.SHARE_SHARED).order_by('-pub_date', 'title')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.info


class TopRecipesFeed(Feed):
    title = settings.OETITLE + _(" Top Recipes")
    link = "/recipe/top/"
    description =_("Top recipes on ") + settings.OETITLE

    def items(self):
        rating_qs = Recipe.objects.extra(select={'rate': '((100/%s*rating_score/(rating_votes+%s))+100)/2' % (Recipe.rating.range, Recipe.rating.weight)})
        return rating_qs.filter(shared=Recipe.SHARE_SHARED).order_by('-rate')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.info

openeats/ingredient/views.py
from django.http import HttpResponse
from models import Ingredient

import json

def autocomplete_ing(request):
    """Used to auto complete ingredient names on the recipe form. This view is called by a jquery script
       returns json list of ten ingredients found
    """
    
    q = request.GET.get('term', '')
    ing_list = Ingredient.objects.filter(title__istartswith=q).values_list('title').distinct().order_by('title')[:10]
    results = []
    for ing_item in ing_list:
        results.append(" ".join(ing_item))
    return HttpResponse(json.dumps(results), mimetype="application/json")

openeats/news/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from models import Entry


def entry(request, slug):
    """returns one news entry"""
    entry = get_object_or_404(Entry, slug=slug)
    return render_to_response('news/entry.html', {'entry': entry}, context_instance=RequestContext(request))


def list(request):
    """returns a list of news stories"""
    entry_list = Entry.objects.all().order_by('pub_date')
    return render_to_response('news/entry_list.html', {'entry_list': entry_list}, context_instance=RequestContext(request))

openeats/recipe_groups/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.generic import ListView
from django.views.generic.edit import  CreateView, UpdateView
from django.core.urlresolvers import reverse_lazy
from models import Course, Cuisine
from openeats.recipe.models import Recipe
from django.contrib.auth.decorators import login_required
from forms import CoursePopForm, CuisinePopForm
from openeats.helpers.form_helper import handlePopAdd


def course_recipes(request, slug):
    """Rectrives the recipe objects in a list that belong to the course passed to the method"""
    course_object = get_object_or_404(Course, slug=slug)
    recipe_list = course_object.recipe_set.filter(shared=Recipe.SHARE_SHARED)
    
    return render_to_response('recipe_groups/recipe_list.html', {'recipe_list': recipe_list, 'category': course_object.title}, context_instance=RequestContext(request))


def cuisine_recipes(request, slug):
    """Retrives the recipe objects in a list that belong to the cuisine passed to the method"""
    cuisine_object = get_object_or_404(Cuisine, slug=slug)
    recipe_list = cuisine_object.recipe_set.filter(shared=Recipe.SHARE_SHARED)
       
    return render_to_response('recipe_groups/recipe_list.html', {'recipe_list': recipe_list, 'category': cuisine_object.title}, context_instance=RequestContext(request))


@login_required
def course_pop(request):
    """Is called via js from the recipe form to allow users to add a new course with out leaving the recipe form"""
    return handlePopAdd(request, CoursePopForm, 'course')


@login_required
def cuisine_pop(request):
    """Is called via js from the recipe form to allow users to add a new cuisine with out leaving the recipe form"""
    return handlePopAdd(request, CuisinePopForm, 'cuisine')


class CourseList(ListView):
    context_object_name = 'course'
    queryset = Course.objects.all()


class CuisineList(ListView):
    context_object_name = 'cuisine'
    queryset = Cuisine.objects.all()


class CourseCreate(CreateView):
    model = Course
    success_url = reverse_lazy('recipe')


class CourseUpdate(UpdateView):
    model = Course


class CuisineCreate(CreateView):
    model = Cuisine
    template_name = 'recipe_groups/course_form.html'
    success_url = reverse_lazy('recipe')


class CuisineUpdate(UpdateView):
    model = Cuisine

openeats/tags/views.py
from taggit.models import Tag, TaggedItem
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404


def recipeTags(request, tag):
    """displays a list of recipes with a giving tag"""
    recipe_tag = get_object_or_404(Tag, slug=tag)
    recipes_tagged = TaggedItem.objects.filter(tag=recipe_tag)
    recipe_list = []
    for recipe in recipes_tagged:
        recipe_list.append(recipe.content_object)

    return render_to_response('tags/recipe_tags.html', {'recipe_list': recipe_list}, context_instance=RequestContext(request))

openeats/templates/profiles/create_profile.html
{% extends 'base.html' %}
{% load i18n %}
{% comment %}This template calls the default form to create a users profile{% endcomment %}
{% block title %}{%trans 'edit' %} {{ profile.user.username }} {%trans 'profile' %} {% endblock %}
{% block content %}
<h1>Edit contact info for {{ user }} </h1>

<form method="POST" action="">{% csrf_token %}
    {{ form }}
    <input type="submit" name="submit" value="Update" id="submit">
</form>
{% endblock %}

openeats/templates/profiles/edit_profile.html
{% extends 'base.html' %}
{% load i18n %}
{% comment %}This template is to edit a users profile{% endcomment %}
{% load gravatar_profile %}
{% block title %}{%trans 'edit' %} {{ profile.user.username }} {%trans 'profile' %} {% endblock %}
{% block content %}

 <h2>edit contact info for {{ user }} </h2>

<div class="row">
  <div class="col-sm-3">
      <div class="thumbnail">
          {% gravatar profile.user 120 %}
          <div class="caption">
              <p><em>{%trans 'To change your profile picture you will need to create/login to' %} <a href="http://en.gravatar.com/">{%trans 'Gravata ' %}r</a>{%trans  'using the same email address you used for this site' %}</em></p>
              <p><a href="/accounts/password/change" target="_blank">{%trans 'Change Password' %}</a></p>
          </div>
      </div>
  </div>
</div>

<form method="POST" action="">{% csrf_token %}
    <div class="control-group">
        <label class="control-label" for="id_{{ form.about.id_for_label }}">about</label>
        <div class="controls">
          {{ form.about }} {{ form.about.errors }}
       </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="id_{{ form.gender.id_for_label }}">gender</label>
        <div class="controls checkbox">
            {{ form.gender }} {{ form.gender.errors }}
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="id_{{ form.about.id_for_location }}">location</label>
        <div class="controls">
          {{ form.location }} {{ form.location.errors }}
       </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="id_{{ form.email.id_for_label }}">email</label>
        <div class="controls">
          {{ form.email }} {{ form.email.errors }}
       </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="id_{{ form.url.id_for_label }}">homepage</label>
        <div class="controls">
          {{ form.url }} {{ form.about.url }}
       </div>
    </div>
    <input type="submit" name="submit" value="update" id="submit">
 </form>
{% endblock %}

openeats/templates/profiles/profile_detail.html
{% extends 'base.html' %}
{% comment %}This template displays the users profile{% endcomment %}
{% load i18n %}
{% load recipe_count %}
{% load gravatar_profile %}
{% block title %}{{ profile.user.username }} {%trans 'profile' %} {% endblock %}

{% block jscript %}
 
 <script type="text/javascript">
    $(function() {
        var hijax = function(panel) {
            $('ul.pagination a', panel).click(function(){
                $(panel).load(this.href, {}, function() {
                    hijax(this);
                });
                return false;
            });
        };
        $("#tabs").tabs({
            ajaxOptions: {
                error: function(xhr, status, index, anchor) {
                    $(anchor.hash).html("Couldn't load this tab.");
                }
            },
            load: function(event, ui) {
                hijax(ui.panel);

            }
        });
    });
</script>

{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-sm-3">
        <div class="thumbnail">
          <h2>{{ profile.user.username }} {%trans 'profile' %}</h2>
          {% if profile.user != request.user %}
            <a href="/follow/add/{{ profile.user.username }}/following/">
            <img src="{{ STATIC_URL }}images/follow-me.png" /></a>
          {% endif %}
          {% gravatar profile.user 120%}
          <div class="caption">
              <h5>{% trans 'info' %}</h5>
                {% if profile.location %}
                    <p><span class="profile-info">{%trans 'location:' %}</span> {{ profile.location }}</p>
                {% endif %}
                {% if profile.gender %}
                    <p><span class="profile-info">{%trans 'gender:' %}</span> {{ profile.gender }}</p>
                {% endif %}
                {% if profile.url %}
                    <p><span class="profile-info">{%trans 'website:' %}</span> <a href="{{ profile.url }}"> {{ profile.url }}</a></p>
                {% endif %}
          </div>
        </div>
    </div>
  </div>

    <div class="well well-sm">
        <h3>{% trans 'all about me' %}</h3>
        <p>{{ profile.about }}</p>
    </div>



     <div id="tabs">
        <ul>
             <li><a href="/recipe/ajaxulist/share/{{ profile.user.username }}/">{%trans 'recipes' %}({{ profile.user.username|recipeCount:'shared'}})</a></li>
            {% if profile.user.username == request.user.username %}
             <li><a href="/recipe/ajaxulist/private/{{ profile.user.username }}/">{%trans 'private recipes' %}({{ profile.user.username|recipeCount:'private'}})</a></li>
             <li><a href="/recipe/ajax-favrecipe/">{%trans 'favorites' %}({{profile.user.storedrecipe_set.count}})</a></li>
             <li><a href="/list/grocery/grocery-ajax/"> {%trans 'grocery list' %}({{profile.user.grocerylist_set.count}})</a></li>
             <li><a href="{%  url 'friends_following' username=profile.user.username %}">{% trans 'followers' %}</a></li>
             <li><a href="{%  url 'friends_feed' username=profile.user.username %}">{% trans 'feed' %}</a></li>
             <li><a href="#settings">{%trans 'settings' %}</a></li>
            {% endif %}

        </ul>
        {% if profile.user.username == request.user.username %}
         <div id="settings">
           <ul>
             <li><a href="/profiles/edit/">{%trans 'edit Profile' %}</a></li>
             <li><a href="/accounts/password/change/">{%trans 'change password' %}</a></li>
             <li><a href="/accounts/logout/">{%trans 'logout' %}</a></li>
           </ul>
         </div>
        {% endif %}
    </div>

</div>
{% endblock %}